### ISSUE TITLE
Chage base image

### ISSUE THREAD

**Issue by gwmoura** [tsuru/base-platform#1]
Guys, what are you think to change the base image `ubuntu-debootstrap:14.04` to `alpine:latest` - https://hub.docker.com/_/alpine/.

Alpine has only 5 MB and ubuntu-debbootstrap has 87 MB. I don't know the implication of this change on running apps, but the company iron.io is using this image for many languages, looks this links:
- https://github.com/iron-io/dockers
- https://github.com/iron-io/dockers/blob/master/base/Dockerfile

Advantages:
- create smaller images for containers
- fast deploy
- fast updates
- fast platform updates
- fast upload images

A simple example:

reference: https://github.com/gliderlabs/docker-alpine/tree/d59b1d8ffd48d19c574bdd88c25b031bc83dfaad#usage

``` dockerfile
FROM ubuntu-debootstrap:14.04
RUN apt-get update -q \
  && DEBIAN_FRONTEND=noninteractive apt-get install -qy mysql-client \
  && apt-get clean \
  && rm -rf /var/lib/apt
ENTRYPOINT ["mysql"]
```

This took 19 seconds to build and yields a 164 MB image:

``` dockerfile
FROM gliderlabs/alpine:3.3
RUN apk add --no-cache mysql-client
ENTRYPOINT ["mysql"]
```

Only 3 seconds to build and results in a 36 MB image!

**Comment by gstpereira** [comment]
We can try to change and make a PR or this change is impossible that happen?

**Comment by andrestc** [comment]
Lots of apps are running using these platforms so changing from ubuntu to alpine might break some people (missing libs and stuff).

We decided to create new platforms using alpine as base. They live in https://github.com/tsuru/alpine-platforms and https://github.com/tsuru/alpine-base-platform. We would love to get some PRs on those!

**Comment by gstpereira** [comment]
Thanks @andrestc I'll make some PR for the alpine-plataforms, let's go!  :)
