### ISSUE TITLE
Update Ubuntu version

### ISSUE THREAD

**Issue by davidkroell** [tsuru/base-platform#9]
Could you take an update of the base image into account?
Either change to a newer version of Ubuntu or go with the minimal Alpine Linux distribution.

When using the PHP platform with the Nginx webserver I noticed that the webserver is very outdatet. I already addressed this in https://github.com/tsuru/platforms/issues/84. I came to the point that without updating the base image, the webserver will never update to a newer version, due to the fact, that Ubuntu 14.04 only supports Nginx 1.4.6 (https://packages.ubuntu.com/trusty/nginx).

Best regards,
David

**Comment by morpheu** [comment]
Already update all platforms to 18.04. Thanks
